linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  enable:
    # Enabled by default (https://golangci-lint.run/usage/linters/#enabled-by-default)
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Additional linters
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - execinquery
    - exportloopref
    - forbidigo
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - importas
    - interfacebloat
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - errname

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/cert-manager/issuer-lib) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
