//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrappedClusterIssuer) DeepCopyInto(out *WrappedClusterIssuer) {
	*out = *in
	in.ClusterIssuer.DeepCopyInto(&out.ClusterIssuer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrappedClusterIssuer.
func (in *WrappedClusterIssuer) DeepCopy() *WrappedClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(WrappedClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WrappedClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WrappedIssuer) DeepCopyInto(out *WrappedIssuer) {
	*out = *in
	in.Issuer.DeepCopyInto(&out.Issuer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WrappedIssuer.
func (in *WrappedIssuer) DeepCopy() *WrappedIssuer {
	if in == nil {
		return nil
	}
	out := new(WrappedIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WrappedIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
