apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-issuer-controller-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system