---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-issuer-controller-role
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - simpleclusterissuers.testing.cert-manager.io/*
  - simpleissuers.testing.cert-manager.io/*
  resources:
  - signers
  verbs:
  - sign
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - testing.cert-manager.io
  resources:
  - simpleclusterissuers
  - simpleissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testing.cert-manager.io
  resources:
  - simpleclusterissuers/status
  - simpleissuers/status
  verbs:
  - patch
