//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The cert-manager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type Issuer interface {
	runtime.Object
	metav1.Object

	GetConditions() []metav1.Condition

	// GetIssuerTypeIdentifier returns a string that uniquely identifies the
	// issuer type. This should be a constant across all instances of this
	// issuer type. This string is used as a prefix when determining the
	// issuer type for a Kubernetes CertificateSigningRequest resource based
	// on the issuerName field. The value should be formatted as follows:
	// "<issuer resource (plural)>.<issuer group>". For example, the value
	// "simpleclusterissuers.issuer.cert-manager.io" will match all CSRs
	// with an issuerName set to eg. "simpleclusterissuers.issuer.cert-manager.io/issuer1".
	GetIssuerTypeIdentifier() string
}

func (cmi *ClusterNativeIssuer) GetConditions() []metav1.Condition {
	conditions := make([]metav1.Condition, 0, len(cmi.Status.Conditions))

	for _, cond := range cmi.Status.Conditions {
		metaCond := metav1.ConditionStatus(string(cond.Status))
		conditions = append(conditions, metav1.Condition{
			Type:               string(cond.Type),
			Status:             metaCond,
			LastTransitionTime: *cond.LastTransitionTime,
			ObservedGeneration: cond.ObservedGeneration,
			Reason:             cond.Reason,
			Message:            cond.Message,
		})
	}

	return conditions
}

func (cmi *ClusterNativeIssuer) GetIssuerTypeIdentifier() string {
	return "clusterissuers.native.cert-manager.io"
}

func (cmi *NativeIssuer) GetConditions() []metav1.Condition {
	conditions := make([]metav1.Condition, 0, len(cmi.Status.Conditions))

	for _, cond := range cmi.Status.Conditions {
		metaCond := metav1.ConditionStatus(string(cond.Status))
		conditions = append(conditions, metav1.Condition{
			Type:               string(cond.Type),
			Status:             metaCond,
			LastTransitionTime: *cond.LastTransitionTime,
			ObservedGeneration: cond.ObservedGeneration,
			Reason:             cond.Reason,
			Message:            cond.Message,
		})
	}

	return conditions
}

func (cmi *NativeIssuer) GetIssuerTypeIdentifier() string {
	return "issuers.native.cert-manager.io"
}
